import type { Metadata } from "next";
import { Encode_Sans} from "next/font/google";
import "./globals.css";
import { Navbar } from "./_Component/Navbar/Navbar";
import Footer from "./_Component/Footer/Footer";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import { Toaster } from "@/components/ui/sonner"
import UserProvider from "images/UserProvider";
import "@fortawesome/fontawesome-free/css/all.min.css";
import CountProvider from "images/CountProvider";
import CountWishlistProvider from "images/CountWishlistProvider";


const Encode_SansFont = Encode_Sans({
  subsets: ["latin"],
  weight: ['100','400','800']
})

export const metadata: Metadata = {
  title: "Shoppee",
  description: "Generated by shoppee",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${Encode_SansFont.className} antialiased min-height: 100dvh`}
      >
        <UserProvider>
        <CountWishlistProvider>
          <CountProvider>
            <Navbar/>
        <main className="p-5">

        {children}
        </main>
        <Toaster/>
        <Footer/>
        </CountProvider>
        </CountWishlistProvider>
        
        </UserProvider>
      </body>
    </html>
  );
}
